---
driver:
  name: vagrant
  customize:
    memory: 4500
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
#  - name: centos-7.0
#  - name: ubuntu-15.04

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[hopsmonitor::install]
      - recipe[hopsmonitor::default]

    attributes:
         graphite:
            default:
                private_ips: ["10.0.2.15"]
                public_ips: ["10.0.2.15"]
         kagent:
            default:
                private_ips: ["10.0.2.15"]
                public_ips: ["10.0.2.15"]
         hopsmonitor:
            default:
                private_ips: ["10.0.2.15"]
                public_ips: ["10.0.2.15"]
         vagrant: true
